services:
  burndown:
    image: burndown:latest
    container_name: burndown
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9042
      - Firefly__FrontChannelBaseAddress=http://localhost:8042
      - Firefly__BackChannelBaseAddress=http://localhost:8042
      - Firefly__RedirectUri=http://localhost:9042/signin-oidc
      - Firefly__ClientId=151
      - Firefly__ClientSecret=i84Q3RTmC6DNjN7ReVo3BUP6ZErRqlaK0asX8EaK
    network_mode: host